sudo: false
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly

before_script:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install -f cargo-travis;
        export PATH=$HOME/.cargo/bin:$PATH;
      fi

script:
  - (cargo test --all --verbose);

after_success:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo coveralls --all;
      fi

